# .github/workflows/send-email.yml
name: Send Email Notification

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 使用一个稳定版本的Node.js

      - name: Install dependencies
        run: npm install nodemailer
      
      - name: Write to a file
        run: echo "Hello GitHub Actions!" > my-output.txt
        
      - name: Verify file content
        run: cat my-output.txt
        
      - name: Run email script
        run: node src/run-task.js
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.MAIL_TO }} # 可以在这里设置收件人
